name: Transfer Docker Image

inputs:
  source_registry:
    required: true
    type: string
  target_registry:
    required: true
    type: string
  source_image:
    required: true
    type: string
  target_image:
    required: true
    type: string

runs:
  using: composite
  steps:
#    - name: Log in to Source Registry
#      uses: docker/login-action@v2
#      with:
#        registry: ${{ inputs.source_registry }}
#        username: ${{ secrets.SOURCE_REGISTRY_USERNAME }}
#        password: ${{ secrets.SOURCE_REGISTRY_PASSWORD }}

#    - name: Log in to Target Registry
#      uses: docker/login-action@v2
#      with:
#        registry: ${{ inputs.target_registry }}
#        username: ${{ secrets.TARGET_REGISTRY_USERNAME }}
#        password: ${{ secrets.TARGET_REGISTRY_PASSWORD }}

    - name: Tag and Push Docker Image to Target
      shell: bash
      run: |
        docker pull ${{ inputs.source_image }}
        #docker tag ${{ inputs.source_image }} ${{ inputs.target_image }}
        ## REMOVE LATER ###
        export image_id=$(uuidgen)
        target=$(echo "${{ inputs.target_image }}" | sed "s/\/.*/\/$image_id:1h/")
        echo "tag & push: $target"
        docker tag ${{ inputs.source_image }} $target
        docker push $target
        ## REMOVE LATER ###
#        docker push ${{ inputs.target_image }}
