name: Transfer Docker Image

inputs:
  source_registry:
    required: true
    type: string
  target_registry:
    required: true
    type: string
  source_image:
    required: true
    type: string
  target_image:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Log in to Source Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.source_registry }}
        username: ${{ secrets.SOURCE_REGISTRY_USERNAME }}
        password: ${{ secrets.SOURCE_REGISTRY_PASSWORD }}

    - name: Pull Docker Image from Source
      uses: docker/cli-action@v1
      with:
        run: docker pull ${{ inputs.source_image }}

    - name: Log in to Target Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.target_registry }}
        username: ${{ secrets.TARGET_REGISTRY_USERNAME }}
        password: ${{ secrets.TARGET_REGISTRY_PASSWORD }}

    - name: Tag and Push Docker Image to Target
      uses: docker/cli-action@v1
      with:
        run: |
          docker tag ${{ inputs.source_image }} ${{ inputs.target_image }}
          docker push ${{ inputs.target_image }}

    - name: Log out from Registries
      uses: docker/logout-action@v1
