name: Detect Updates and Trigger Transfers

on:
  push:
    paths:
      - containers/** # Monitor changes to directory
      - .github/workflows/**

jobs:
  process-image-list:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.parse-images.outputs.image_list }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@v1.0.1
      with:
        version: v0.46.0

    - name: Parse Image List
      id: parse-images
      run: |
        echo "Parsing images-list.json..."
        IMAGE_LIST=$(zarf tools yq -r '.components[].images[]' containers/zarf.yaml)
        IMAGE_LIST_JSON=$(echo "[${IMAGE_LIST//$'\n'/,}]")
        echo "image_list=$IMAGE_LIST_JSON" >> $GITHUB_ENV  # Set the list as an environment variable

  transfer-images:
    needs: process-image-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.process-image-list.outputs.image_list) }}  # Reference the output of the read-docker-images job

    steps:
    - name: Debug Matrix
      run: |
        echo "Matrix content: ${{ matrix.include }}"

    - name: Call Reusable Workflow for Transfer
      uses: ./.github/workflows/transfer-docker-image.yaml
      with:
        source_image: ${{ matrix.source_image }}
        target_image: ${{ matrix.source_image }}
