name: Detect Updates and Trigger Transfers

on:
  push:
    paths:
      - containers/** # Monitor changes to directory

jobs:
  process-image-list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@v1.0.1
      with:
        version: v0.46.0

    - name: Parse Image List
      id: parse-images
      run: |
        echo "Parsing images-list.json..."
        IMAGE_LIST=$(zarf tools yq -r '.components[].images[]' containers/zarf.yaml)
        MATRIX_JSON="["
        for IMAGE in $IMAGE_LIST; do
          SOURCE_REGISTRY="docker.io"
          SOURCE_IMAGE="$IMAGE"
          TARGET_REGISTRY="ttl.sh"  # Predict target registry
          TARGET_IMAGE="$(echo "$IMAGE" | sed "s|$SOURCE_REGISTRY/|$TARGET_REGISTRY/|g")
          MATRIX_JSON="$MATRIX_JSON{\"source_image\":\"$SOURCE_IMAGE\",\"target_image\":\"$TARGET_IMAGE\"},"
        done
        MATRIX_JSON="${MATRIX_JSON%,}]" # Remove trailing comma and close array
        echo "Matrix JSON: $MATRIX_JSON"
        echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  transfer-images:
    needs: process-image-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.process-image-list.outputs.matrix) }}

    steps:
    - name: Call Reusable Workflow for Transfer
      uses: ./.github/workflows/transfer-docker-image.yaml
      with:
        source_image: ${{ matrix.source_image }}
        target_image: ${{ matrix.target_image }}
