# Update the image list and target registry below to run workflow
name: Detect Updates and Trigger Transfers

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  process-image-list:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.parse-images.outputs.image_list }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@v1.0.1
      with:
        version: v0.46.0

  transfer-images:
    needs: process-image-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source_image:
        ### UPDATE THIS
          - "docker.io/busybox:1.36.0"
          - "docker.io/alpine:3.18.10"
        ### UPDATE THIS
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set target image from source image
        id: set_target_image
        run: |
          ### UPDATE THIS
          echo "target_registry=ttl.io" >> $GITHUB_ENV
          ### UPDATE THIS
          source_image="${{ matrix.source_image }}"
          echo "source_registry=$(echo ${source_image} | cut -d'/' -f1)" >> $GITHUB_ENV
          target_image="${source_image/$source_registry/$target_registry}"
          echo "Target image is: $target_image"
          echo "target_image=$target_image" >> $GITHUB_ENV


      - name: Call Reusable Workflow for Transfer
        uses: ./.github/actions/transfer-docker-image
        with:
          source_registry: ${{ env.source_registry }}
          source_image: ${{ matrix.source_image }}
          target_registry: ${{ env.target_registry }}
          target_image: ${{ env.target_image }}
