name: Detect Updates and Trigger Transfers

on:
  push:
    paths:
      - containers/** # Monitor changes to directory
      - .github/workflows/**

jobs:
  process-image-list:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.get-images.outputs.image_list }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@v1.0.1
      with:
        version: v0.46.0

    - name: Parse Image List
      id: parse-images
      run: |
        echo "Parsing images-list.json..."
        IMAGE_LIST=$(zarf tools yq -r '.components[].images[]' containers/zarf.yaml)
        echo "image_list=[${IMAGE_LIST//$'\n'/,}]" >> $GITHUB_ENV  # Set the list to GITHUB_ENV
        echo "image_list: $image_list"

  transfer-images:
    needs: process-image-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source_image: ${{ fromJson(env.IMAGE_LIST) }}  # Using the environment variable

    steps:
    - name: Debug Matrix
      run: |
        echo "Matrix content: ${{ matrix.include }}"

    - name: Call Reusable Workflow for Transfer
      uses: ./.github/workflows/transfer-docker-image.yaml
      with:
        source_image: ${{ matrix.source_image }}
        target_image: ${{ matrix.source_image }}
