# Update the image list and target registry below to run workflow
name: Detect Updates and Trigger Transfers

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  transfer-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source_image:
          ### UPDATE THIS ###
          - "docker.io/busybox:1.36.0"
          - "docker.io/alpine:3.18.10"
          ### UPDATE THIS ###
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set target image from source image
        id: set_target_image
        run: |
          ### UPDATE THIS ###
          export TARGET_REGISTRY="$(echo "ttl.sh")"
          echo "target_registry=$TARGET_REGISTRY" >> $GITHUB_ENV
          ### UPDATE THIS ###
          export SOURCE_IMAGE="${{ matrix.source_image }}"
          echo "source_image=$SOURCE_IMAGE" >> $GITHUB_ENV
          export SOURCE_REGISTRY="$(echo ${source_image} | cut -d'/' -f1)"
          echo "source_registry=$SOURCE_REGISTRY" >> $GITHUB_ENV
          export TARGET_IMAGE="${SOURCE_IMAGE/$SOURCE_REGISTRY/$TARGET_REGISTRY}"
          echo "Target image is: $TARGET_IMAGE"
          echo "target_image=$TARGET_IMAGE" >> $GITHUB_ENV

      - name: Call local actions workflow for transfer
        uses: ./.github/actions/transfer-docker-image
        with:
#          source_registry: ${{ env.source_registry }}
          source_image: ${{ matrix.source_image }}
          target_registry: ${{ env.target_registry }}
          target_image: ${{ env.target_image }}
