name: Detect Updates and Trigger Transfers

on:
  push:
    paths:
      - .github/workflows/**

jobs:
  process-image-list:
    runs-on: ubuntu-latest
    outputs:
      image_list: ${{ steps.parse-images.outputs.image_list }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Zarf
      uses: defenseunicorns/setup-zarf@v1.0.1
      with:
        version: v0.46.0

  transfer-images:
    needs: process-image-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        source_image:
          - "docker.io/busybox:1.36.0"
          - "docker.io/alpine:3.18.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set target image from source image
        id: set_target_image
        run: |
          source_image="${{ matrix.source_image }}"
          target_image="${source_image/docker.io/ttl.io}"
          echo "Target image is: $target_image"
          echo "target_image=$target_image" >> $GITHUB_ENV

      - name: Call Reusable Workflow for Transfer
        uses: ./.github/workflows/transfer-docker-image.yaml
        with:
          source_image: ${{ matrix.source_image }}
          target_image: ${{ env.target_image }}
